# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c

before_install:

- gem install cocoapods --quiet
- pod --version
- pod setup --silent
- pod repo update --silent

script:

- pod lib lint

- cd Example
- pod update
- cd ..

- xctool -workspace Example/JNKeychain.xcworkspace -scheme 'JNKeychain' -sdk iphonesimulator build
- xcodebuild -workspace Example/JNKeychain.xcworkspace -scheme 'JNKeychainTests' -sdk iphonesimulator clean test
