# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c

before_install:

- gem install cocoapods --quiet
- pod --version
- pod setup --silent
- pod repo update --silent

script:

- pod lib lint
- pod update
- xctool test -workspace Example/JNKeychain.xcworkspace -scheme 'JNKeychain' -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
